services:
  streamvix:
    image: qwertyuiop8899/streamvix:latest
    container_name: streamvix
    ports:
      - "7860:7860"
    environment:
      - ADDON_BASE_URL=https://streamv-stremio-giy.duckdns.org
      - BOTHLINK=true
      - MFP_URL=https:https://mediaflo.duckdns.org  # MediaFlow Proxy URL
      - MFP_PASSWORD=2323gio            # MediaFlow Proxy password
      - TMDB_API_KEY=710711c7c7eee4b7f3293c331e5587bf        # https://www.themoviedb.org/settings/api
      
      # Anime (opzionale)
      - ANIMEUNITY_ENABLED=true
      - ANIMESATURN_ENABLED=true
      
      # Live TV & Eventi Sportivi
      - Enable_Live_TV=true
      
      # Eventi Sportivi Avanzati (opzionale - configurazione automatica se omesso)
      # - SPON_PROG_URL=https://sportzonline.st/prog.txt
      # - RBTV_DISCOVERY_BEFORE_MIN=15
      # - STREAMED_ENABLE=1
      
      # Installazione Locale/VPS (opzionale - per FHD VixSrc synthetic)
      # - ADDON_BASE_URL=https://streamvix.tuodominio.com
    restart: always
    
  # Watchtower per aggiornamenti automatici immagine (opzionale)
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: always




